集成nodex
leansocket/nodex-0 pull request #1
Opened 2020-10-09 12:43 UTC by rubysynack

2020-10-09 15:07 UTC, chqilin requested changes

2020-10-09 15:07 UTC, chqilin commented on package.json
> +    "nodex-cli": "^0.2.0"
nodex-cli可以放在devDependencies里面

2020-10-09 15:07 UTC, chqilin commented on src/data.js
> +    await nodex.mysql.init(args.mysql);
用变量保存mysql

2020-10-09 15:07 UTC, chqilin commented on src/serv.js
>  };
可以将库代码集成到nodex.libs。这样可以与nodex.runtime对应。

2020-10-10 02:14 UTC, rubysynack commented on package.json
> +    "nodex-cli": "^0.2.0"
生产环境(pm2)也要用到nodex-cli，所以放在dependencies是正确的。

2020-10-10 15:49 UTC, chqilin requested changes
将nodex.libs的引用和nodex.runtime的引用都放在模块顶部，作为模块的全局变量。这样的编程风格更统一和简洁。

2020-10-10 15:49 UTC, chqilin commented on src/data.js
> +    const mysql = nodex.libs.mysql;
将mysql保存为一个全局变量，因为会被data层所有方法重复使用。

2020-10-10 15:49 UTC, chqilin commented on src/serv.js
> +    nodex.libs.log.init(nodex.runtime.args.app.name);
在这里初始化日志不太好，放在app初始化的第一行。

2020-10-10 15:49 UTC, chqilin commented on src/serv.js
>  exports.init = async function (args) {
serv的init和start是不是可以合并。

2020-10-11 14:10 UTC, rubysynack commented on src/serv.js
>  exports.init = async function (args) {
init和start代表不同的语义，我们应该显式暴露init方法给用户使用。

2020-10-15 03:27 UTC, merged